### ISSUE TITLE
IPC-Shareable-1.13 contains new file ipc.pl

### ISSUE THREAD

**Issue by jplesnik** [stevieb9/ipc-shareable#25]
The tarball IPC-Shareable-1.13.tar.gz contains new file ipc.pl. 
I found that the file isn't in git repository. However, the file is listed in MANIFEST.
https://github.com/stevieb9/ipc-shareable/blob/master/MANIFEST#L12

What is this file for?

**Comment by stevieb9** [comment]
Testing, I'm sure, but I will investigate. Sorry for the late response!
