### ISSUE TITLE
Double size is not compatible (-Duselongdouble?)

### ISSUE THREAD

**Issue by eserte** [stevieb9/ipc-shareable#5]
On some of my smokers the test suite fails like this:
```
Double size is not compatible at /opt/perl-5.26.2D/lib/site_perl/5.26.2/x86_64-linux-ld/Storable.pm line 471, at /home/cpansand/.cpan/build/2021061006/IPC-Shareable-1.00-3/blib/lib/IPC/Shareable.pm line 546.
t/71-unspawn.t .......... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
```
This is a perl compiled with `-Duselongdouble`. I can image that it's also failing on quadmath perls (but I don't have any of these available).

**Comment by stevieb9** [comment]
Will compile a version with `-Duselongdouble` and see what's happening here. Don't yet know if this problem is with this software, or `Storable`

**Comment by eserte** [comment]
I guess that a Storable-serialized float (NV) has the double size when created with a uselongdouble perl. I think the easiest is to just skip the test for -Duselongdouble perls, or in general, for all perls with `$Config{nvsize}!=8`.

**Comment by stevieb9** [comment]
Thanks for that. I'll get that implemented.

**Comment by stevieb9** [comment]
Fixed in https://github.com/stevieb9/ipc-shareable/commit/8727edd2a1bf6a1f0fdfdebe8149724fc8cdbee5
